### ISSUE TITLE
Progress bar not working with flac files

### ISSUE THREAD

**Issue by mn54-9** [devsnd/cherrymusic#603] opened 2015-12-22 08:01 UTC
Hello,

I've recently added .flac files in my library. The progress bar doesn't show where we are in the song's playback. Everything else works fine: playback, counters, clicking on the blue bar forwards the playback to that point, etc.

I'm running firefox 43.0.1 on linux, cherrymusic version 0.36.0.

![capture du 2015-12-22 08 57 54](https://cloud.githubusercontent.com/assets/10062217/11950756/a747ddf4-a88b-11e5-87ee-9a75940b1f96.png)

This doesn't seem like an urgent bug to fix, but it would be nice to have.

Continue with the great work!

**Comment by anthonyryan1** [comment] 2015-12-30 20:33
This issue also seems to affect MP3s (and possibly other formats) when the "Limit audio bitrate" setting is set to anything except "Unlimited". This makes me think the progress bar is non-functional for everything that's transcoded for playback.

**Comment by anthonyryan1** [comment] 2015-12-30 22:18
I've done a bit more research into this.

The reason the progress bar doesn't fill up is because the AudioElement.duration is set to Infinity when an Accept-Range is not returned.

If we were able to provide a Content-Length header, we can show the buffering progress (but not yet skip to new positions). But that is hard to know given we're transcoding content as needed, a few naieve approaches at approximating this value in relation to the bitrate, but that proved insufficient.

**Comment by devsnd** [comment] 2016-01-10 20:37
Hey Michael, Hi Anthony,

Thanks for your interest and research!

This is actually a long standing issue (see #275), and as Anthony says, it is indeed not so trivial to solve. See [this post](https://github.com/devsnd/cherrymusic/issues/275#issuecomment-27386106) for a more thorough explaination of the underlying issue.

I will close this issue as it is a duplicate of #275.

**Closed by devsnd** 2016-01-10 20:37 UTC
