### ISSUE TITLE
Gapless playback (not xfade)

### ISSUE THREAD

**Issue by kli0rf** [devsnd/cherrymusic#635] opened 2016-08-09 10:31 UTC
Hi,

i wonder if there is a possibility to make cherymusic's playback gapless? And i mean not the crossfade, i mean the gaps, which happens in between of mixed tracks. There is lotta dj mixes with the tracks splitted, i.e. with no silence in the end of the track and no silence in the start of a track. Any other player plays such a playlist without gaps between tracks, so you can listen to the mix without any silent pause when the new track starts. Is that possible on cherrymusic?

**Comment by devsnd** [comment] 2016-09-17 15:59
Hey @kli0rf,

Sorry that is currently not possible with cherrymusic. I am working on a new CM client that might be able to do so in the future but right now, no.

Closing as a duplicate of https://github.com/devsnd/cherrymusic/issues/394

**Closed by devsnd** 2016-09-17 15:59 UTC
