### ISSUE TITLE
Encoding error in file names ?

### ISSUE THREAD

**Issue by SeeDborg** [devsnd/cherrymusic#611] opened 2016-01-22 15:45 UTC
I have trouble updating the database, having this king of error :

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/__init__.py", line 980, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 287-288: ordinal not in range(128)
Call stack:
  File "/usr/lib/python3.4/threading.py", line 888, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/cherrymusic/cherrymusicserver/util.py", line 49, in wrapper
    result = func(*args, **kwargs)
  File "/opt/cherrymusic/cherrymusicserver/sqlitecache.py", line 471, in full_update
    self.update_db_recursive(cherry.config['media.basedir'], skipfirst=True)
  File "/opt/cherrymusic/cherrymusicserver/sqlitecache.py", line 540, in update_db_recursive
    self.register_file_with_db(item.infs)
  File "/opt/cherrymusic/cherrymusicserver/sqlitecache.py", line 312, in register_file_with_db
    log.e(_("wrong encoding for filename '%s' (%s)"), fileobj.relpath, e.__class__.__name__)
  File "/opt/cherrymusic/cherrymusicserver/log.py", line 126, in error
    _get_logger().error(msg, *args, **kwargs)
Message: "wrong encoding for filename '%s' (%s)"
Arguments: ('Les paradis disponibles/7 - Mon P\udcc3\udca8re Ce H\udcc3\udca9ros.mp3', 'UnicodeEncodeError')
```

I think it's related to the caracters in my files' names. How can I fix this ?

**EDIT:** Formatted code properly. Please use Markdown next time. -- 6arms1leg

**Comment by gbrito** [comment] 2016-02-03 14:10
I had a similar problem with Cherrymusic, the problem is the locales not being passed correctly to python.
Although the locales in my environment were set to en_US.UTF-8 the Cherrymusic wasn't getting the proper ones.

In my system i has starting Cherrymusic with the command:

`python cherrymusic &`

The command `python` was bind to python2.7. Since i have python 2.7 and python 3.2 i tried with both of them and python 3.2 was getting the necessary locales.
You can test the commands in your system through the python console and see what happens in the different python versions.

```
goncalo@fr19286:~$ python3.2
Python 3.2.3 (default, Feb 20 2013, 14:44:27)
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getlocale()
('en_US', 'UTF-8')

goncalo@fr19286:~$ python
Python 2.7.3 (default, Mar 13 2014, 11:03:55)
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getlocale()
(None, None)
```

Now i start the Cherrymusic with the command `python3.2 cherrymusic &` and have no problems.

**Comment by mobiuszero1** [comment] 2016-02-05 00:16
Thanks @gbrito  I was having the same issue and this appears to have fixed it for me.

**Comment by 6arms1leg** [comment] 2016-04-01 17:10
@SeeDborg , did this fix the issue for you, too (so I can close this issue)?

**Comment by 6arms1leg** [comment] 2016-04-03 12:26
OK, I tried same thing on my server which gave the same result. Also, I remembered we had similar issues in the past (see https://github.com/devsnd/cherrymusic/issues/368#issuecomment-28640120), even one that is still open (#315).
@devsnd , is the latter one related (or even a duplicate) or did we lost Python >= 2.6 support completely somewhere along the way? :scream:

**Comment by devsnd** [comment] 2016-05-23 05:11
@6arms1leg The python2 support seems to be as broken as it always was: It requires the system to ber set up perfectly, whereas python 3 just works.

I have however still one change in mind that might fix a lot of those issues. Some time ago I read about the option for python to encode characters that include invalid byte-sequences using a so-called replacement character. ([see here for the documentation](https://docs.python.org/2.7/library/codecs.html#codec-base-classes)). This might take care of many of those problems (mostly hiding them, but who cares, as long as it works ;)

**Comment by IvanBayan** [comment] 2016-10-04 21:11
I think i faced with same bug,  Mozilla/5.0 (X11; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0 stops playing, Chromium	53.0.2785.143 stops and resumes every few minutes.
PS
Thanks for cherrymusic

**Comment by tilboerner** [comment] 2016-10-24 20:43
Sorry, I'm late to the party! :dancer: @SeeDborg (the OP) has a Python 3 bug, and it's a **duplicate of #595**: See the obstinate `\xdc` byte there in that mangled unicode? I'm closing this ticket in favor of the older one. Please take all related discussion there.

@IvanBayan: If CherryMusic stops playing in the middle of your tracks, you have a different problem. An audio transcoding one, if I had to guess. Decoding the filename in your output with UTF-8 leads to some text Google translates as Serbian, so I think you're fine. If your issue persists, could you please open a new ticket? Just copy and paste your comment; if you have any output from the server console to add, that would be great. ^^

**Closed by tilboerner** 2016-10-24 20:43 UTC
Labels: bug
