### ISSUE TITLE
Page Title Blinking with Vivaldi/Chromium

### ISSUE THREAD

**Issue by ycawidro** [devsnd/cherrymusic#664] opened 2017-03-08 04:57 UTC
Hello,

I am using cherrymusic 0.38 (but it was the same on 0.37.2) and the title keep blinking from : 
- if music not playing 
CherryMusic <-> http://<server>/<path>
- if music is playing
Artist - Title <-> http://<server>/<path>

Server : Debian jessie armhf
Client : Ubuntu 12.04 amd64 with Vivaldi Browser (1.7.735.46 (Stable channel) (64-bit)), Chrome/56.0.2924.88 Safari/537.36 Vivaldi/1.7.735.46

I have search through the source to find where I can stop this blinking as I find it quite annoying.
(it kept catching my eyes while being on other browser tabs).
Can you help me ? (It might be browser related but I have deactivated transcode and Firefox cannot play my mp3 which is fair)

Yanik

**Comment by tilboerner** [comment] 2017-03-08 10:20
That sounds annoying, sorry! I'm not sure which title you're talking about. Is it the document title (window title bar / tab name)? Otherwise, could you take a screenshot and circle the area?

**Comment by ycawidro** [comment] 2017-03-08 10:23
Sorry if I was not clear, I meant the "Tab Title" (document.title I may say in Javascript)

**Comment by tilboerner** [comment] 2017-03-08 18:06
Thanks for clarifying. I can reproduce the blinking in a current build of Vivaldi, and I found the cause. The CherryMusic client [updates the document title][] once a second so it can display the current song:

[updates the document title]: https://github.com/devsnd/cherrymusic/blob/8dd9deb0548a7ef7cff35f2b82f6e49f93b7e045/res/js/playlistmanager.js#L877

```js
$('title').text(tabtitle);
```
Something that jQuery does behind the scenes (is it unsetting the text before setting it?) causes this hiccup. Using plain JS does not produce the flickering:

```js
document.title = tabtitle;
```

@devsnd: Any reason why we should not be using the simple, plain Javascript here? Otherwise, I'll make this the fix.

**Comment by ycawidro** [comment] 2017-03-09 01:20
Thank you this is a neat hack.

**Comment by devsnd** [comment] 2017-03-12 12:55
@tilboerner No there's no reason why we shouldn't use plain javascript (I didn't put much thought into it i guess), feel free to patch it 💃

**Comment by tilboerner** [comment] 2017-03-13 09:22
@devsnd In that case we're golden, the patch is already in the devel branch. Closing.

**Closed** 2017-03-13 09:22 UTC
Labels: bug, UI
